project_name: omnimimic_all_small
run_name: omnimimic_all_small

#data dir
data_dir: /iris/u/jyang27/rlds_data

# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 256
epochs: 1000
gpu_ids: [0]
num_workers: 12
lr: 1e-4
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 4
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0

# model params
model_type: nomad
vision_encoder: nomad_vint
encoding_size: 256
obs_encoder: efficientnet-b3
attn_unet: False
cond_predict_scale: False
mha_num_attention_heads: 8
mha_num_attention_layers: 8
mha_ff_dim_factor: 8
down_dims: [256, 512, 1024, 2048]
wrist_image_only: True

# diffusion model params
num_diffusion_iters: 10

# mask 
goal_mask_prob: 0.0

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 5
alpha: 1e-4

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 3
  max_dist_cat: 20

# action output params
len_traj_pred: 8
learn_angle: False

# dataset specific parameters
image_size: [64, 64] # width, height

# logging stuff
## =0 turns off
print_log_freq: 100 # in iterations
image_log_freq: 0 #0 # in iterations
num_images_log: 8 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.25
wandb_log_freq: 10 # in iterations
eval_freq: 5 # in epochs
